### PR TITLE
[1.5.x] Convert username (email) to lowercase

### PR DESCRIPTION
**Pull request by finagin**
This is necessary because this field is converted to lower case during authorization.

### CODE REVIEW

**Comment by lee-to** [comment]
now you can customize authentication and use your own login field, which can allow uppercase, so I think this change is superfluous

**Comment by finagin** [comment]
this is bad because it doesn't let me try moonshine right out of the box by following the instructions in the documentation

**Comment by finagin** [comment]
it is a matter of data consistency in the package

if the user wants to change the logic, he will do it everywhere

now for simple work you need to understand what is wrong and change it in one of the classes

**Comment by lee-to** [comment]
we'll think about it

**Pull request closed without merging**
